import type { Metadata } from "next";
import "./globals.css";
import { workSans400 } from "./fonts";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={workSans400.className}>{children}</body>
    </html>
  );
}
